main/urls.py
from django.urls import path
from .views import home, myurls, allurls, shortened, redirect_to_original

urlpatterns = [
    path("Shorty/", home, name="home"),
    path("shorty/", home, name="home"),
    path("myurls/", myurls, name="myurls"),
    path("allurls/", allurls, name="allurls"),
    path("shortened/<int:pk>/", shortened, name="shortened"),
    path("<str:custom_url>/", redirect_to_original, name="redirect_to_original"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, re_path, register_converter
from .case_insensitive import CaseInsensitiveConverter
from django.conf import settings
from django.conf.urls.static import static
from landing.views import landing, download_file, WLASL, CV, allprojects
from django.urls import path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.urls import include, path

# Register the CaseInsensitiveConverter
register_converter(CaseInsensitiveConverter, 'ci')


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", landing, name="landing"),
    path("allprojects/", allprojects, name="allprojects"),
    path("WLASL/", WLASL, name="WLASL"),
    path("CV/", CV, name="CV"),
    path("cv/", CV, name="CV"),
    path("download/<str:filename>/", download_file, name="download_file"),
    path("", include("users.urls")),
    path("", include("main.urls")),
    # path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico')))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_URL)

users/urls.py
from django.urls import path
from .views import (
    customSignup,
    customLogin,
    customLogout,
    profile,
    customadmin,
    allusers,
    activate,
    change_password,
    reset_password,
    verifyReset,
    delete_account,
)

urlpatterns = [
    path("signup/", customSignup, name="signup"),
    path("login/", customLogin, name="login"),
    path("logout/", customLogout, name="logout"),
    path("profile/", profile, name="profile"),
    path("deleteaccount/", delete_account, name="deleteaccount"),
    path("customadmin/", customadmin, name="customadmin"),
    path("allusers/", allusers, name="allusers"),
    path("activate/<uidb64>/<token>/", activate, name="activate"),
    path("changepassword/", change_password, name="changepassword"),
    path("resetpassword/", reset_password, name="resetpassword"),
    path("reset/<uidb64>/<token>/", verifyReset, name="reset"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
import os


class CustomUser(AbstractUser):
    """
    Custom user model.
    """

    def image_upload_to(self, filename):
        """
        Upload image to user directory.
        """
        return os.path.join("profiles", self.username, filename)

    email = models.EmailField(unique=True)
    activation_email_sent = models.BooleanField(default=False)
    image = models.ImageField(
        default="default/default.png", upload_to=image_upload_to)

    def save(self, *args, **kwargs):
        """
        Resize the image and delete old image before saving the user instance.
        """
        if self.pk:
            old_instance = CustomUser.objects.get(pk=self.pk)
            if self.image and self.image != old_instance.image:

                # if the old image is not default.png, delete it
                if old_instance.image.name != "default/default.png":
                    old_instance.image.delete(save=False)

        # Resize the new image before saving
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    SetPasswordForm,
)
from django.contrib.auth import get_user_model
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox
from django.contrib.auth.forms import SetPasswordForm as BaseSetPasswordForm
from django.contrib.auth.forms import PasswordResetForm as BasePasswordResetForm
from django.utils.translation import gettext_lazy as _


class UserSignUpForm(UserCreationForm):
    """
    Custom User Sign Up Form
    """

    username = forms.CharField(
        max_length=150,
        help_text="Required. 150 characters or fewer. Letters, digits, and @/./+/-/_ only.",
        widget=forms.TextInput(attrs={"placeholder": "Username"}),
    )

    email = forms.EmailField(
        help_text="Required. Add a valid email address.",
        required=True,
        widget=forms.EmailInput(attrs={"placeholder": "Email"}),
    )

    first_name = forms.CharField(
        max_length=30,
        help_text="Your first name.",
        widget=forms.TextInput(attrs={"placeholder": "First Name"}),
    )

    last_name = forms.CharField(
        max_length=30,
        help_text="Your last name.",
        widget=forms.TextInput(attrs={"placeholder": "Last Name"}),
    )

    password1 = forms.CharField(
        help_text="Enter a password. It should not be too similar to your other personal information or a commonly used password.",
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
    )

    password2 = forms.CharField(
        help_text="Enter the same password as before, for verification.",
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]

    def save(self, commit=True):
        user = super(UserSignUpForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()

        return user


class UserLoginForm(AuthenticationForm):
    """
    Custom User Login Form
    """

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Username or Email"}
        ),
        label="Username or Email",
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        )
    )

    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())


class UserUpdateForm(forms.ModelForm):
    """
    Custom User Update Form
    """

    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "first_name", "last_name", "image"]


# class SetPasswordForm(SetPasswordForm):
#     """
#     Custom Set Password Form
#     """
#     class Meta:
#         model = get_user_model()
#         fields = ["new_password1", "new_password2"]


class SetPasswordForm(BaseSetPasswordForm):
    """
    Custom Set Password Form
    """

    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": _("Enter new password")}
        ),
        label=_("New password"),
        help_text=_(
            "Your password must be at least 8 characters long and contain a mix of letters, digits, and symbols."
        ),
    )

    new_password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": _("Confirm new password")}
        ),
        label=_("Confirm new password"),
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = get_user_model()
        fields = ["new_password1", "new_password2"]


class PasswordResetForm(BasePasswordResetForm):
    """
    Custom Password Reset Form
    """

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs["placeholder"] = _("Enter your email")
        self.fields["email"].help_text = _(
            "Enter the email address associated with your account."
        )

    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    class Meta:
        fields = ["email"]

templates/users/activate_account.html
{% autoescape off %}
    Hi {{ user }},
    Please click on the link below to activate your account:
    {{ protocol }}://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/users/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <link rel="stylesheet" href="{% static "css/shorty-style.css" %}">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
        <script src="{% static "fontawesomefree/js/all.min.js" %}"></script>
        <link rel="stylesheet" href="{% static "fontawesomefree/css/all.min.css" %}">
        <!-- favicon -->
        <link rel="icon" type="image/x-icon" href="{% static "images/fav.png" %}">
        <title>Admin - Shorty</title>
    </head>
    <body>
        <div class="container">
            <div class="left">
                <a href="{% url "home" %}">
                    <div class="logo">
                        <img src="{% static "images/logo.png" %}" alt="Shorty Logo" srcset="">
                    </div>
                </a>
                <div class="navcontainer">
                    <div class="spacer"></div>
                    <div class="navpanel">
                        <ul>
                            <div class="curve-bg">
                                <div class="dummy"></div>
                            </div>
                            <div class="curve-bg">
                                <li class="">
                                    <a href="{% url "home" %}">New</a>
                                </li>
                            </div>
                            <div class="curve-bg">
                                <li class="">
                                    <a href="{% url "myurls" %}">My URLs</a>
                                </li>
                            </div>
                            <div class="curve-bg">
                                <li class="top-active">
                                    <a href="{% url "allurls" %}">All URLs</a>
                                </li>
                            </div>
                            <div class="curve-bg">
                                <li class="active">
                                    <a href="{% url "customadmin" %}">Admin</a>
                                </li>
                            </div>
                            <div class="curve-bg">
                                <li class="bottom-active">
                                    <a href="{% url "allusers" %}">Users</a>
                                </li>
                            </div>
                            <div class="curve-bg">
                                <div class="dummy"></div>
                            </div>
                        </ul>
                    </div>
                </div>
                <div class="account">
                    <ul>
                        <li>
                            {% if user.is_authenticated %}
                                <a href="{% url 'profile' %}">
                                    <div class="profile-container">
                                        <div class="photo">
                                            <img src="{{ user.image.url }}" alt="Profile Photo" class="profile-photo">
                                        </div>
                                        <div class="info">
                                            <div class="username">{{ user.username }}</div>
                                            <div class="email">
                                                <i>{{ user.email }}</i>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="right">
                <div class="mobile-logo">
                    <img src="{% static "images/shorty_logo.png" %}" alt="Shorty Logo" srcset="">
                </div>
                <div class="users-form-container">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="message-container">
                                <p class="message">{{ message|safe|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% if inactive_users %}
                        <h2>Sign Up Requests</h2>
                        <table>
                            <tr>
                                <th class="original-url">Username</th>
                                <th>Email</th>
                                <th class="original-url">First Name</th>
                                <th class="original-url">Last Name</th>
                                <th>&nbsp;</th>
                                <th>&nbsp;</th>
                            </tr>
                            {% for user in inactive_users %}
                                <form action="" class="users-form" method="post">
                                    {% csrf_token %}
                                    <tr>
                                        <td class="original-url">{{ user.username }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="original-url">{{ user.first_name }}</td>
                                        <td class="original-url">{{ user.last_name }}</td>
                                        <td>
                                            <input type="hidden" name="user_id" value="{{ user.id }}">
                                            <input type="hidden" name="action_approve" value="approve">
                                            <button type="submit" name="action" value="approve" class="form-btn">Approve</button>
                                        </td>
                                        <td>
                                            <input type="hidden" name="user_id" value="{{ user.id }}">
                                            <input type="hidden" name="action_delete" value="delete">
                                            <button type="submit" name="action" value="delete" class="form-btn">Delete</button>
                                        </td>
                                    </tr>
                                </form>
                            {% endfor %}
                        </table>
                    {% else %}
                        <h2>No inactive users found.</h2>
                    {% endif %}
                </div>
                {% include "main/bottomNav.html" %}
            </div>
        </div>
    </body>
</html>

templates/users/changepassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <link rel="stylesheet" href="{% static "css/shorty-style.css" %}">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
        <script src="{% static "fontawesomefree/js/all.min.js" %}"></script>
        <link rel="stylesheet" href="{% static "fontawesomefree/css/all.min.css" %}">
        <!-- favicon -->
        <link rel="icon" type="image/x-icon" href="{% static "images/fav.png" %}">
        <title>Profile - Shorty</title>
    </head>
    <body>
        <div class="container">
            <div class="left">
                <a href="{% url "home" %}">
                    <div class="logo">
                        <img src="{% static "images/logo.png" %}" alt="Shorty Logo" srcset="">
                    </div>
                </a>
                <div class="navcontainer">
                    <div class="spacer"></div>
                    <div class="navpanel">
                        <ul>
                            <div class="curve-bg">
                                <div class="dummy"></div>
                            </div>
                            <div class="curve-bg">
                                <li class="">
                                    <a href="{% url "home" %}">New</a>
                                </li>
                            </div>
                            <div class="curve-bg">
                                <li class="">
                                    <a href="{% url "myurls" %}">My URLs</a>
                                </li>
                            </div>
                            {% if user.groups.all.0.name == 'admin' %}
                                <div class="curve-bg">
                                    <li class="">
                                        <a href="{% url "allurls" %}">All URLs</a>
                                    </li>
                                </div>
                                <div class="curve-bg">
                                    <li class="">
                                        <a href="{% url "customadmin" %}">Admin</a>
                                    </li>
                                </div>
                                <div class="curve-bg">
                                    <li class="">
                                        <a href="{% url "allusers" %}">Users</a>
                                    </li>
                                </div>
                            {% endif %}
                            <div class="curve-bg">
                                <div class="dummy"></div>
                            </div>
                        </ul>
                    </div>
                </div>
                <div class="account">
                    <ul>
                        <li>
                            {% if user.is_authenticated %}
                                <a href="{% url 'profile' %}">
                                    <div class="profile-container profile-active">
                                        <div class="photo">
                                            <img src="{{ user.image.url }}" alt="Profile Photo" class="profile-photo">
                                        </div>
                                        <div class="info">
                                            <div class="username">{{ user.username }}</div>
                                            <div class="email">
                                                <i>{{ user.email }}</i>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="right">
                <div class="mobile-logo">
                    <img src="{% static "images/shorty_logo.png" %}" alt="Shorty Logo" srcset="">
                </div>
                <div class="form-container">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="message-container">
                                <p class="message">{{ message|safe|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form action=""
                          method="post"
                          enctype="multipart/form-data"
                          class="login-form">
                        {% csrf_token %}
                        <h2>Change Password</h2>
                        {% for field in form %}<div class="form-field">{{ field }}</div>{% endfor %}
                        <button type="submit">Change</button>
                    </form>
                </div>
                {% include "main/bottomNav.html" %}
            </div>
        </div>
    </body>
</html>

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <link rel="stylesheet" href="{% static "css/shorty-style.css" %}">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
                      <!-- favicon -->
        <link rel="icon" type="image/x-icon" href="{% static "images/fav.png" %}">
        <title>Login - Shorty</title>
    </head>
    <body>
        <div class="form-container">
            {% if messages %}
                {% for message in messages %}
                    <div class="message-container">
                        <p class="message">{{ message|safe|escape }}</p>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" class="login-form" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'captcha' %}
                        {# Exclude captcha field #}
                        <div class="form-field">{{ field }}</div>
                    {% endif %}
                {% endfor %}
                <div class="captcha-container">
                    {# Wrap the captcha field in a container #}
                    {{ form.captcha }}
                </div>
                <button type="submit">Login</button>
                <p>
                    Forgot Password? <a href="{% url "resetpassword" %}">Reset</a>
                </p>
                <p>
                    Don't have an account? <a href="{% url "signup" %}">Sign Up</a>
                </p>
            </form>
        </div>
    </body>
</html>

templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <link rel="stylesheet" href="{% static "css/shorty-style.css" %}">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
        <script src="{% static "fontawesomefree/js/all.min.js" %}"></script>
        <link rel="stylesheet" href="{% static "fontawesomefree/css/all.min.css" %}">
        <!-- favicon -->
        <link rel="icon" type="image/x-icon" href="{% static "images/fav.png" %}">
        <title>Profile - Shorty</title>
    </head>
    <body>
        <div class="container">
            <div class="left">
                <a href="{% url "home" %}">
                    <div class="logo">
                        <img src="{% static "images/logo.png" %}" alt="Shorty Logo" srcset="">
                    </div>
                </a>
                <div class="navcontainer">
                    <div class="spacer"></div>
                    <div class="navpanel">
                        <ul>
                            <div class="curve-bg">
                                <div class="dummy"></div>
                            </div>
                            <div class="curve-bg">
                                <li class="">
                                    <a href="{% url "home" %}">New</a>
                                </li>
                            </div>
                            <div class="curve-bg">
                                <li class="">
                                    <a href="{% url "myurls" %}">My URLs</a>
                                </li>
                            </div>
                            {% if user.groups.all.0.name == 'admin' %}
                                <div class="curve-bg">
                                    <li class="">
                                        <a href="{% url "allurls" %}">All URLs</a>
                                    </li>
                                </div>
                                <div class="curve-bg">
                                    <li class="">
                                        <a href="{% url "customadmin" %}">Admin</a>
                                    </li>
                                </div>
                                <div class="curve-bg">
                                    <li class="">
                                        <a href="{% url "allusers" %}">Users</a>
                                    </li>
                                </div>
                                <div class="curve-bg">
                                    <div class="dummy"></div>
                                </div>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="account">
                    <ul>
                        <li>
                            {% if user.is_authenticated %}
                                <a href="{% url 'profile' %}">
                                    <div class="profile-container profile-active">
                                        <div class="photo">
                                            <img src="{{ user.image.url }}" alt="Profile Photo" class="profile-photo">
                                        </div>
                                        <div class="info">
                                            <div class="username">{{ user.username }}</div>
                                            <div class="email">
                                                <i>{{ user.email }}</i>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="right">
                <div class="mobile-logo">
                    <img src="{% static "images/shorty_logo.png" %}" alt="Shorty Logo" srcset="">
                </div>
                <div class="form-container">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="message-container">
                                <p class="message">{{ message|safe|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form action=""
                          method="post"
                          enctype="multipart/form-data"
                          class="login-form">
                        {% csrf_token %}
                        <h2>Profile</h2>
                        <label for="id_image" class="profile-image">
                            <img id="preview-image" src="{% if form.instance.image %}{{ form.instance.image.url }}{% else %}{% static "images/default_photo.jpg" %}{% endif %}" alt="Profile Image" width="200px" height="200px">
                            <input type="file"
                                   name="image"
                                   accept="image/*"
                                   id="id_image"
                                   onchange="previewImage(event)">
                        </label>
                        <br>
                        <input type="text"
                               name="username"
                               value="{{ form.instance.username }}"
                               maxlength="150"
                               required
                               id="id_username">
                        <br>
                        <input type="email"
                               name="email"
                               value="{{ form.instance.email }}"
                               maxlength="320"
                               required
                               id="id_email">
                        <br>
                        <input type="text"
                               name="first_name"
                               value="{{ form.instance.first_name }}"
                               maxlength="150"
                               id="id_first_name">
                        <br>
                        <input type="text"
                               name="last_name"
                               value="{{ form.instance.last_name }}"
                               maxlength="150"
                               id="id_last_name">
                        <button type="submit">Save</button>
                        <div class="buttons">
                            <a href="{% url 'changepassword' %}">Change Password</a>
                            {% if user.groups.all.0.name != 'admin' %}
                                <a href="{% url 'deleteaccount' %}">Delete Account</a>
                            {% endif %}
                            <a href="{% url 'logout' %}">Logout</a>
                        </div>
                    </form>
                </div>
                {% include "main/bottomNav.html" %}
            </div>
        </div>
        <script>
            function previewImage(event) {
                var reader = new FileReader();
                reader.onload = function() {
                    var output = document.getElementById('preview-image');
                    output.src = reader.result;
                };
                reader.readAsDataURL(event.target.files[0]);
            }
        </script>
    </body>
</html>